-- Clean existing categories to avoid duplicates (optional, use with caution)
-- TRUNCATE TABLE public.categories CASCADE;

-- Insert categories from CATEGORY_FILTERS
INSERT INTO public.categories (slug, label, group_name)
VALUES
('alugar-casa-apartamento', 'Alugar casas - Apartamentos', 'Imóveis'),
('carros-usados', 'Carros usados', 'Veículos'),
('vagas-emprego', 'Vagas de emprego', 'Empregos'),
('estagios-trainee', 'Estágios - Trainee', 'Empregos'),
('curriculos', 'Anunciar currículo - Procurar emprego', 'Empregos'),
('cuidador-idosos', 'Acompanhante idosos - Enfermeira', 'Serviços'),
('empregada-domestica', 'Empregada doméstica - Diarista', 'Serviços'),
('trabalho-em-casa', 'Trabalhar em casa', 'Empregos'),
('servicos-domesticos', 'Trabalhos domésticos', 'Serviços'),
('babas', 'Babás', 'Serviços'),
('servicos-informatica', 'Serviços de informática', 'Serviços'),
('cursos-idiomas', 'Cursos de idiomas', 'Cursos'),
('animais-estimacao-venda', 'Animais estimação à venda', 'Animais estimação'),
('celulares-acessorios', 'MP3 - Ipod - Celulares', 'Multimédia & Eletrónicos'),
('acompanhantes', 'Acompanhantes', 'Relacionamento'),
('motos-scooters', 'Motos - Scooters', 'Veículos'),
('caminhoes-comerciais', 'Caminhões - Comerciais', 'Veículos'),
('onibus-venda', 'Ônibus usados', 'Veículos'),
('barcos-lanchas', 'Barcos - Lanchas', 'Veículos'),
('pecas-acessorios', 'Acessórios e serviços', 'Veículos'),
('caravanas-trailers', 'Caravanas - Trailers', 'Veículos'),
('comprar-imovel', 'Apartamentos - Casas venda', 'Imóveis'),
('aluguel-temporada', 'Aluguel temporada', 'Imóveis'),
('lancamentos-imobiliarios', 'Empreendimentos Imóveis', 'Imóveis'),
('garagens-venda', 'Estacionamentos - Garagens', 'Imóveis'),
('imoveis-exterior', 'Casas venda exterior', 'Imóveis'),
('aluguel-temporada-exterior', 'Aluguel temporada exterior', 'Imóveis'),
('terrenos-exterior', 'Terrenos venda Exterior', 'Imóveis'),
('pontos-comerciais', 'Imóveis comerciais - Escritórios', 'Imóveis'),
('terrenos-venda', 'Terrenos - Lotes', 'Imóveis'),
('aluguel-quarto', 'Quartos - Compartilhar', 'Imóveis'),
('troca-de-imoveis', 'Troca de casas - Apartamentos', 'Imóveis'),
('moveis-decoracao', 'Móveis-Camas-Cadeiras', 'Para a sua casa'),
('utilidades-domesticas', 'Decoração casa', 'Para a sua casa'),
('eletrodomesticos', 'Eletrodomésticos usados', 'Para a sua casa'),
('colecionaveis', 'Artigos de coleção', 'Lazer e Hobbies'),
('equipamentos-profissionais', 'Equipamentos profissionais', 'Multimédia & Eletrónicos'),
('esportes-lazer', 'Artigos esportivos - Bicicletas', 'Lazer e Hobbies'),
('artesanato', 'Artesanato - Feito à mão', 'Lazer e Hobbies'),
('presentes', 'Idéias para presentes', 'Lazer e Hobbies'),
('instrumentos-musicais', 'Instrumentos musicais', 'Lazer e Hobbies'),
('gastronomia', 'Bebidas - Comidas', 'Serviços'),
('computadores-perifericos', 'Notebooks - Computadores usados', 'Multimédia & Eletrónicos'),
('games-livros-filmes', 'DVD - Video Games - Livros - CD', 'Lazer e Hobbies'),
('joias-relogios', 'Antiguidades - Jóias', 'Moda e beleza'),
('roupas-calcados', 'Roupas e acessórios', 'Moda e beleza'),
('beleza-saude', 'Produtos beleza - Saúde', 'Moda e beleza'),
('outros-produtos', 'Diversos', 'Para a sua casa'),
('turismo', 'Serviços turismo - Agência turismo', 'Serviços'),
('traducoes', 'Traduções - Serviços de traduções', 'Serviços'),
('mudancas-fretes', 'Mudanças - Frete', 'Serviços'),
('profissionais-liberais', 'Profissionais liberais', 'Serviços'),
('reformas-manutencao', 'Reparo - Conserto - Reforma', 'Serviços'),
('saude-beleza', 'Bem-Estar - Saúde - Beleza', 'Serviços'),
('esoterismo', 'Astrologia - Serv. Espirituais', 'Serviços'),
('outros-servicos', 'Outros serviços', 'Serviços'),
('cursos-informatica', 'Cursos de informática', 'Cursos'),
('cursos-profissionalizantes', 'Capacitação profissional', 'Cursos'),
('aulas-particulares', 'Professores particulares', 'Cursos'),
('esportes-danca', 'Aulas de ginástica', 'Cursos'),
('musica-teatro', 'Aulas música-Teatro-Dança', 'Cursos'),
('outros-cursos', 'Outros cursos', 'Cursos'),
('adocao-animais', 'Adoção animais de estimação', 'Animais estimação'),
('servicos-animais', 'Veterinários-Serviços-Acessórios', 'Animais estimação'),
('acompanhantes-trans', 'Acompanhantes trans', 'Relacionamento'),
('acompanhantes-masculinos', 'Acompanhantes masculinos', 'Relacionamento'),
('amizade', 'Procurar amigos', 'Relacionamento'),
('namoro', 'Procurar amor', 'Relacionamento'),
('mulher-procura-homem', 'Mulher procura homem', 'Relacionamento'),
('homem-procura-mulher', 'Homem procura mulher', 'Relacionamento'),
('mulher-procura-mulher', 'Mullher procura mulher', 'Relacionamento'),
('homem-procura-homem', 'Homem procura homem', 'Relacionamento'),
('encontros', 'Encontros casuais', 'Relacionamento')
ON CONFLICT (slug) DO UPDATE
SET label = EXCLUDED.label,
    group_name = EXCLUDED.group_name;
